create database GESTIONMETASAPP;

USE GESTIONMETASAPP;


CREATE TABLE METAS (
    ID_META INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(80),
    FECHA_CREACION DATETIME,
    TOTAL_TAREAS INT,
    PORCENTAJE DECIMAL(5, 2)
);

CREATE TABLE TAREA (
    ID_TAREA INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(80),
    ESTADO VARCHAR(40),
    FECHA_CREACION DATETIME,
    IMPORTANTE BIT,
    ID_META INT,
    FOREIGN KEY (ID_META) REFERENCES METAS(ID_META)
);